// <auto-generated />
using System;
using EventPhoto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace EventPhoto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPhoto.Domain.Entities.AiSearchAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("embedding_version");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("MatchesFound")
                        .HasColumnType("integer")
                        .HasColumnName("matches_found");

                    b.Property<int>("SearchDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("search_duration_ms");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TopMatchCategory")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("top_match_category");

                    b.Property<float?>("TopSimilarityScore")
                        .HasColumnType("real")
                        .HasColumnName("top_similarity_score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("was_successful");

                    b.HasKey("Id");

                    b.HasIndex("SearchedAt")
                        .HasDatabaseName("IX_ai_search_analytics_searched_at");

                    b.HasIndex("EventId", "SearchedAt")
                        .HasDatabaseName("IX_ai_search_analytics_event_searched_at");

                    b.ToTable("ai_search_analytics", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.ApplicationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BrandTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("dark")
                        .HasColumnName("brand_theme");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultEventGalleryMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_event_gallery_mode");

                    b.Property<Guid?>("DefaultWatermarkProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_watermark_profile_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("EnableFaceRecognitionByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_face_recognition_by_default");

                    b.Property<bool>("EnableWatermarkByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_watermark_by_default");

                    b.Property<string>("Facebook")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("facebook");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instagram");

                    b.Property<bool>("IsFaceSearchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_face_search_enabled");

                    b.Property<bool>("IsWatermarkEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_watermark_enabled");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#6366f1")
                        .HasColumnName("primary_color");

                    b.Property<string>("PublicBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("public_base_url");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#8b5cf6")
                        .HasColumnName("secondary_color");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("server_name");

                    b.Property<int>("ServerPort")
                        .HasColumnType("integer")
                        .HasColumnName("server_port");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("studio_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("whats_app");

                    b.HasKey("Id");

                    b.ToTable("application_settings", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.DownloadLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("EventId");

                    b.HasIndex("PhotoId");

                    b.ToTable("download_logs", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowFaceSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_face_search");

                    b.Property<bool>("AllowGalleryBrowsing")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_gallery_browsing");

                    b.Property<string>("ClientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("EnableFaceRecognition")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_face_recognition");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<float>("FaceMatchThreshold")
                        .HasColumnType("real")
                        .HasColumnName("face_match_threshold");

                    b.Property<int?>("GalleryRecentCount")
                        .HasColumnType("integer")
                        .HasColumnName("gallery_recent_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("photo_count");

                    b.Property<string>("QrCodePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("qr_code_path");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("qr_code_url");

                    b.Property<bool>("RestrictDownloadsToMatchedPhotos")
                        .HasColumnType("boolean")
                        .HasColumnName("restrict_downloads_to_matched_photos");

                    b.Property<string>("ThumbnailFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_folder");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("venue_name");

                    b.Property<string>("WatchFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("watch_folder");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("AverageQualityScore")
                        .HasColumnType("real")
                        .HasColumnName("average_quality_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("photo_count");

                    b.Property<Vector>("RepresentativeEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(512)")
                        .HasColumnName("representative_embedding");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_face_clusters_event_id");

                    b.ToTable("face_clusters", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bounding_box");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("arcface-512-v1")
                        .HasColumnName("embedding_version");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("FaceCountInPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("face_count_in_photo");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<float>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(50f)
                        .HasColumnName("quality_score");

                    b.Property<string>("QualityTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("quality_tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_face_embeddings_event_id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_face_embeddings_photo_id");

                    b.HasIndex("EventId", "QualityTier")
                        .HasDatabaseName("IX_face_embeddings_event_quality_tier");

                    b.ToTable("face_embeddings", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FailureType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_face_processing_jobs_photo_id");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_face_processing_jobs_event_status");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_face_processing_jobs_retry_eligible")
                        .HasFilter("status = 'Failed'");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("IX_face_processing_jobs_pending_priority")
                        .HasFilter("status IN ('Pending', 'Queued')");

                    b.ToTable("face_processing_jobs", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.GuestFaceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("match_count");

                    b.Property<DateTimeOffset?>("SearchCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("search_completed_at");

                    b.Property<int>("SearchDurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("search_duration_ms");

                    b.Property<DateTimeOffset?>("SearchStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("search_started_at");

                    b.Property<DateTimeOffset?>("SelfieDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selfie_deleted_at");

                    b.Property<Vector>("SelfieEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(512)")
                        .HasColumnName("selfie_embedding");

                    b.Property<string>("SelfieHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selfie_hash");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_guest_face_sessions_expires_at");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("IX_guest_face_sessions_token");

                    b.HasIndex("EventId", "SelfieHash")
                        .HasDatabaseName("IX_guest_face_sessions_event_selfie_hash");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_guest_face_sessions_event_status");

                    b.HasIndex("ExpiresAt", "SelfieDeletedAt")
                        .HasDatabaseName("IX_guest_face_sessions_retention")
                        .HasFilter("selfie_deleted_at IS NULL");

                    b.ToTable("guest_face_sessions", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("FaceIndexRetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("face_index_retry_count");

                    b.Property<int>("FaceIndexStatus")
                        .HasColumnType("integer")
                        .HasColumnName("face_index_status");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("original_path");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_path");

                    b.Property<int>("ThumbnailStatus")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnail_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OriginalPath")
                        .IsUnique();

                    b.HasIndex("FaceIndexStatus", "IsDeleted")
                        .HasDatabaseName("IX_photos_face_index_status")
                        .HasFilter("face_index_status = 1");

                    b.HasIndex("ThumbnailStatus", "IsDeleted");

                    b.HasIndex("EventId", "IsDeleted", "CapturedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_photos_event_paged");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.PhotoMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("SimilarityScore")
                        .HasColumnType("real")
                        .HasColumnName("similarity_score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("SessionId", "PhotoId")
                        .IsUnique()
                        .HasDatabaseName("IX_photo_matches_session_photo");

                    b.HasIndex("SessionId", "SimilarityScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_photo_matches_session_score");

                    b.ToTable("photo_matches", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.WatermarkConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApplyOnDownload")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_on_download");

                    b.Property<bool>("ApplyOnPreview")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_on_preview");

                    b.Property<float>("BackgroundOpacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.2f)
                        .HasColumnName("background_opacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FontName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("font_name");

                    b.Property<bool>("IncludeDownloadDate")
                        .HasColumnType("boolean")
                        .HasColumnName("include_download_date");

                    b.Property<bool>("IncludeEventName")
                        .HasColumnType("boolean")
                        .HasColumnName("include_event_name");

                    b.Property<bool>("IncludeStudioName")
                        .HasColumnType("boolean")
                        .HasColumnName("include_studio_name");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<float>("Opacity")
                        .HasColumnType("real")
                        .HasColumnName("opacity");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scale");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("style");

                    b.Property<string>("Template")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("template");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#FFFFFF")
                        .HasColumnName("text_color");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_watermark_configurations_event_id");

                    b.ToTable("watermark_configurations", (string)null);
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.AiSearchAnalytics", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.DownloadLog", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPhoto.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceCluster", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceEmbedding", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.FaceProcessingJob", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPhoto.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.GuestFaceSession", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.Photo", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", "Event")
                        .WithMany("Photos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.PhotoMatch", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPhoto.Domain.Entities.GuestFaceSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.WatermarkConfiguration", b =>
                {
                    b.HasOne("EventPhoto.Domain.Entities.Event", null)
                        .WithOne()
                        .HasForeignKey("EventPhoto.Domain.Entities.WatermarkConfiguration", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventPhoto.Domain.Entities.Event", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
